### PR TITLE
Add Synonyms and Query rules APIs

### LINKED ISSUE #2288: Add synonyms and query rules APIs
**Elasticsearch version** (`bin/elasticsearch --version`): 8.10.0

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 8.10.0

**Description of the problem including expected versus actual behavior**: The synonyms and query rules APIs have been added to the JavaScript client but still need to be added to the Python client. They should have gotten updated with 8.10 work but it looks like there may be additional work to do. 

Also per https://github.com/elastic/elasticsearch-py/pull/2269 there is some manual work required to add these APIs to the docs.

### PR DESCRIPTION
**Pull request by pquentin**
Closes #2288 

The first commit applies generation and `nox -rs format`, while the second one contains my manual fixes. Tested as follows:

```python3
from elasticsearch import Elasticsearch

# Start with `docker run -p 9200:9200 -it -e xpack.security.enabled=false -e discovery.type=single-node docker.elastic.co/elasticsearch/elasticsearch:8.10.0-SNAPSHOT`
es = Elasticsearch("http://localhost:9200")


es.synonyms.put_synonym(
    id="my-synonyms-set",
    synonyms_set=[
        {"id": "test-1", "synonyms": "hello, hi"},
        {"synonyms": "bye, goodbye"},
        {"id": "test-2", "synonyms": "test => check"},
    ],
)
print(es.synonyms.get_synonyms_sets())

es.query_ruleset.put(
    ruleset_id="my-ruleset",
    query_ruleset={
        "rules": [
            {
                "rule_id": "my-rule1",
                "type": "pinned",
                "criteria": [
                    {
                        "type": "contains",
                        "metadata": "user.query",
                        "values": ["marvel", "dc"],
                    },
                    {"type": "exact", "metadata": "user.country", "values": ["us"]},
                ],
                "actions": {"ids": ["id1", "id2"]},
            }
        ]
    },
)
print(es.query_ruleset.list())
```

Note that `es.query_ruleset.put` is weird, I would have expected to be able to use `es.query_ruleset.put(ruleset_id="my-ruleset", rules=[...])` instead as is idiomatic for the 8.x client. Any thoughts on that @kderusso?

### CODE REVIEW

**Comment by kderusso** [comment]
@pquentin Thanks for adding this. This is odd, I can put in an issue to improve it for 8.11. There may already be other client updates to go along with it as it's in tech preview.

**Comment by pquentin** [comment]
This issue was supposed to be fixed by https://github.com/elastic/elasticsearch-specification/pull/2242 but @Anaethelion is also seeing the same issue in Go, which likely means we need an additional fix in elasticsearch-specification.

**Comment by kderusso** [comment]
Thanks @pquentin. I think this should resolve it? https://github.com/elastic/elasticsearch-specification/pull/2276

**Comment by JoshMock** [comment]
Was DMing with @pquentin about this, figured I'd put it on the PR itself to register my confusion openly. :laughing: 

What is the difference between 99654780039d2d78dbbb0c5cea648e3ca07b4cdd and 5abe9cfaf1130ce75e45fa5bc1521a22a80d6320? Both have the same exact number of lines changed, but they differ in ways that are hard to see immediately, mostly because it's so many lines changed. Also: is @pquentin a high-performing genius that he was able to modify thousands of lines of code in a relatively short period of time?

**Comment by JoshMock** [comment]
Never mind. Github is apparently lying to me today. :scream: I have reloaded those diffs in my browser multiple times and suddenly, just now, the diffs changed completely. I may be going crazy.

**Review by JoshMock — APPROVED** [review]

**Comment by pquentin** [comment]
@kderusso With your fix, I can now write the following code:

```
es.query_ruleset.put(
    ruleset_id="my-ruleset",
    rules={
        "rule_id": "my-rule1",
        "type": "pinned",
        "criteria": [
            {
                "type": "contains",
                "metadata": "user.query",
                "values": ["marvel", "dc"],
            },
            {"type": "exact", "metadata": "user.country", "values": ["us"]},
        ],
        "actions": {"ids": ["id1", "id2"]},
    },
)
```

Thanks!

**Review by kderusso — APPROVED** [review]
Thank you for making this fix!

**Pull request merged**
