### PR TITLE
Add resource type and resource id in TransportError Traceback

### PR DESCRIPTION
**Pull request by mazzma12**
Hi @fxdgear. 
I modified the `TransportErrorException` class for #906 . I changed the str formatting with % into the `str.join()` method. I found it more flexible to deal with empty strings and extra commas. Let me know if you think it is a problem (I checked the tests and it passed)

### CODE REVIEW

**Comment by mazzma12** [comment]
@fxdgear ?

**Comment by fxdgear** [comment]
Jenkins test this please

**Comment by fxdgear** [comment]
@mazzma12 Could you please signt he CLA? 

Your tests are passing. It just failed cause some python3.3 weirdness (which is ok cause I'm removing this element from the test matrix cause 3.3 is EOL'd)

**Comment by mazzma12** [comment]
@fxdgear Happy to contribute, even as small it could be. Signed !

**Pull request merged**
