### PR TITLE
Fix issures 560

### PR DESCRIPTION
**Pull request by fatelei**
If params in kwargs and params is None, kwargs.get('params') is `False`
If params not kwargs, kwargs.get('params') is `False`

### CODE REVIEW

**Comment by karmi** [comment]
Hi @fatelei, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch-py/pull/563.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by fatelei** [comment]
https://github.com/elastic/elasticsearch-py/issues/560

**Comment by fatelei** [comment]
@karmi I have added missing email address

**Comment by HonzaKral** [comment]
My question is how would `params` be `None`? For that to happen someone would explicitly have to pass it into an api method which is not supported or documented. Do you have a use case you are trying to solve?

Thank you!

**Pull request closed without merging**
