### PR TITLE
Adds Python client suppport for Elasticsearch 7.5.1

### PR DESCRIPTION
**Pull request by viglia**
Python client for Elasticsearch 7.5.1

### CODE REVIEW

**Comment by viglia** [comment]
@HonzaKral , thanks for the feedback. 

When you say "please do not exactly copy the ES version" do you mean in the `setup.py` and `__init__.py` or that I shouldn't generate from tag linking to patch version.
Should I generate from 7.5.0 instead of 7.5.1 ?

**Comment by HonzaKral** [comment]
yes, `7.5.0` or even `7.2.0` which is the next version in the line of python versions.

**Comment by viglia** [comment]
@philkra please can you clarify and give me a feedback? I've been told to skip [7.2...7.4] and jump to 7.5.1.

**Comment by HonzaKral** [comment]
If you wish to stick to the version, go ahead, but I don't like committing to something that is not sustainable - if we have to do a bugfix release afte `7.5.1` we will have to release `7.5.2` when then Elasticsearch releases `7.5.2` we will be out of sync and there is nothing we can do. At that point I prefer to be explicit about the (possible) divergence. But up to @philkra of course

**Comment by philkra** [comment]
@viglia , please use `7.5.0`. @HonzaKral explained our motives perfectly, we "only" follow up to the `major`.`minor` of Elasticsearch, giving us room to provide fixes in patch versions if necessary. Thanks @HonzaKral and @viglia for tackling `7.5.0`.

**Comment by viglia** [comment]
@HonzaKral @philkra ok, perfect. Then if everyone is fine with this I will close this PR and regenerate pointing to ES 7.5.0 and create a new PR

**Comment by HonzaKral** [comment]
You should keep using `7.5.1` version of elasticsearch, just the version of `elasticsearch-py` should be `7.5.0`

**Comment by philkra** [comment]
thank you @HonzaKral . That's the way to go @viglia .

**Pull request closed without merging**
