### PR TITLE
Remove product verification

### PR DESCRIPTION
**Pull request by sftim**
Allow requests against any Elasticsearch-like API.

This reverts pull request https://github.com/elastic/elasticsearch-py/pull/1623

### CODE REVIEW

**Comment by sftim** [comment]
Also relevant to #1648

**Comment by sftim** [comment]
Getting this one in before @elasticmachine learns how to auto-reject them

**Comment by orenmazor** [comment]
booourns. I believed in you, @sftim

**Comment by JPrevost** [comment]
Oh look, we got a no comment close. Glad they are willing to discuss this... who's gonna fork?

**Comment by sftim** [comment]
https://github.com/elastic/elasticsearch-py/issues/1676#issuecomment-896255707 suggests an alternative patch with similar aims

**Comment by orenmazor** [comment]
> [#1676 (comment)](https://github.com/elastic/elasticsearch-py/issues/1676#issuecomment-896255707) suggests an alternative patch with similar aims

yeah it's inevitable. this is damage. we'll route around this one way or another 🤷

**Comment by sftim** [comment]
https://github.com/elastic/elasticsearch-py/issues/1639#issuecomment-883319286 explains(?) some of the background for the behavior that this PR reverts.

**Pull request closed without merging**
