### PR TITLE
Remove duplicate arguments in documentation

### PR DESCRIPTION
**Pull request by mortenhauberg**
As agreed in elastic/elasticsearch-py#1163

### CODE REVIEW

**Comment by sethmlarson** [comment]
Change looks good, can you commit the changes that would be applied to `elasticsearch/client` as well :)

**Comment by mortenhauberg** [comment]
Yes - just need to figure out why I see extra spaces in the generated code

**Comment by sethmlarson** [comment]
Maybe you need to update your local `7.x` branch? You could try hitting the "Update branch" and then doing a `git pull origin dedupe-arguments` locally.

**Comment by mortenhauberg** [comment]
I think that was it, @sethmlarson.

Thank you very much for your help

**Comment by sethmlarson** [comment]
@mortenhauberg Any time! :heart: I'll give you a mention the next time we release :) If you find any other issues you want to work on I'll be sure to give guidance as well.

**Pull request merged**
