### PR TITLE
Add cluster doc code examples

### PR DESCRIPTION
**Pull request by anniegale9538**
Hello!

I'm adding cluster doc code examples per #2429

Thanks, @pquentin you're a hero!

cc @stefnestor

### CODE REVIEW

**Review by pquentin — APPROVED** [review]
This looks great, thank you! And a great start towards adding more cluster docs examples. And of course, you're the hero, not me.

The only issue is the CLA check. You don't have to sign one as an Elastic employee, but for this to work you have to use your elastic.co address, which you are not doing, see here: https://github.com/elastic/elasticsearch-py/commit/2bcbf9a20a34e2afef65b4621924d97cdd49cd31.patch. You'll have to amend your commit to include the correct email and force push, I'm happy to explain more if you'd like.

**Comment by stefnestor** [comment]
👋 @pquentin, thanks 💚!  Could you kindly explain a bit more 🙏? 

I think I got us close but not quite and I'm not sure how to fix. Annie was moving between two Github accounts (personal @scranberryjam to Elastician @anniegale9538 ) and signed the CLA agreement under both Github usernames (though the second one which we believe is attached to this PR - since we were doing the commit together zooming sharing her work computer's screen - was CLA-signed after the above message popped up). 

Could the problem be I missed [setting Annie's Git PR email address](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address) which is what's needed to connect to the CLA agreement? E.g. [Git Blame](https://git-scm.com/docs/git-blame) exposing email via `-e` doesn't list Annie's personal/work email 😕 
```
elasticsearch-py$ git branch
* (HEAD detached at upstream/annie/adding_to_files_to_generate)

elasticsearch-py$ git blame -e docs/examples/1cecd4d87a92427175157d41859df2af.asciidoc
2bcbf9a20 (<anniehansen@Annies-MacBook-Pro.local> 2024-02-24 11:35:45 -0700  1) // cluster/allocation-explain.asciidoc:10
```

**Comment by anniegale9538** [comment]
@stefnestor @pquentin I am wondering if it happened because I had "Keep my email addresses private" marked under my email on my anniegale9538 github account 😞 I unclicked that and am verifying my user.email now!

**Comment by pquentin** [comment]
Sorry for the delay! Indeed the issue here is the email in the git commit, not the GitHub user. You're going to have to amend the commit to include the correct email, and then do a force push:

```bash
git commit --amend --author="Annie Hansen <YOUREMAIL@elastic.co>"
git push --force-with-lease
```

And to be sure you don't hit this issue for your next PRs, make sure to fix the email globally too:

```bash
git config --global user.name "Annie Hansen"
git config --global user.email "YOUREMAIL@elastic.co"
```

https://www.git-tower.com/learn/git/faq/change-author-name-email is a good reference on that topic.

Hope that helps! If not, I'm also happy to assist more.

**Comment by anniegale9538** [comment]
YES!

Author: Annie Hansen ***@***.***>
> Date:   Tue Feb 27 18:57:51 2024 -0700
>
>     adding cluster doc code examples
>

I went a bit if a different root because it wasn't loving  git commit
--amend --author="Annie Hansen ***@***.***>"

I did a git reset from main, checked out the changes from my original
commit and just recommitted everything. It does leave a dangling commit,
but I am under the impression --append has a similar result, if that is
wrong, my apologies!

**Review by pquentin — APPROVED** [review]
Thank you! LGTM.

**Pull request merged**
