### PR TITLE
Pass scroll and scroll_id in the request body instead of as query params in scan

### PR DESCRIPTION
**Pull request by jtyoung**
Addresses issue #971

### CODE REVIEW

**Comment by fxdgear** [comment]
Jenkins year this please

**Comment by Winterflower** [comment]
Hi @jtyoung - thanks very much for your PR! Just going to run our CI process on it to make sure tests pass etc.

**Comment by Winterflower** [comment]
Jenkins test this please

**Comment by fabiopedrosa** [comment]
@Winterflower since all tests did pass, can we get this merged?

**Comment by Winterflower** [comment]
@fabiopedrosa sorry for the delay in replying! Just checking to see no other regressions will happen if this is moved to body (as it was before).
Thanks @jtyoung for the PR!

**Pull request merged**
