### PR TITLE
Fix sniffer_timeout typo in async transport

### LINKED ISSUE #1423: AsyncElasticsearch transport uses sniff_timeout instead of sniffer_timeout
We can see that in sync version of Elasticsearch transport everything is according to docs (if `sniffer_timeout` is set - we use it):
https://github.com/elastic/elasticsearch-py/blob/8106c0eefc023990a7bf7eb6bc3887bd815e41c4/elasticsearch/transport.py#L227

But when we see async version - there is a typo (`sniff_timeout` is used instead of `sniffer_timeout`)
https://github.com/elastic/elasticsearch-py/blob/8106c0eefc023990a7bf7eb6bc3887bd815e41c4/elasticsearch/_async/transport.py#L135

Can send the PR to fix this if it is not intentional.

### PR DESCRIPTION
**Pull request by HarrySky**
Closes #1423

### CODE REVIEW

**Comment by HarrySky** [comment]
I am in process of signing Contributor Agreement, English is not my native language and I don't get what **Title** field refers to? Is it "Mr/Mrs" or "Software Developer" as Job Title or some other title? Some help would be appreciated :confused:

**Comment by sethmlarson** [comment]
@HarrySky I believe that field is meant to be Mr/Mrs/Ms, etc

**Comment by HarrySky** [comment]
@sethmlarson thank you, signed :smile:

**Review by sethmlarson — APPROVED** [review]
LGTM, thank you!

**Comment by HarrySky** [comment]
@sethmlarson do you have a release schedule somewhere?
When this fix can be expected to be uploaded to PyPI? :smile: (I am using 7.9.1 right now, since my ELK stack is 7.9.1, but I read that only major version matters, right?)

**Comment by sethmlarson** [comment]
The Elastic Stack releases pretty frequently :) I'll update this issue when it's out.

**Comment by sethmlarson** [comment]
Release is out :P

**Pull request merged**
