### PR TITLE
ssl_show_warn option added

### PR DESCRIPTION
**Pull request by alvarolmedo**

### CODE REVIEW

**Comment by elasticcla** [comment]
Hi @alvarolmedo, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch-py/pull/913.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by alvarolmedo** [comment]
email added

**Comment by alvarolmedo** [comment]
Closes issue #914

**Comment by alvarolmedo** [comment]
does this PR be right yet?

**Comment by fxdgear** [comment]
jenkins test this please

**Comment by alvarolmedo** [comment]
Hi again,
I've check the links to your CI and the matrix a jobs executed and failed:
https://clients-ci.elastic.co/job/elastic+elasticsearch-py+pull-request/33/
About the tests with python2.7 and ES version 6.0.1 works fine in my local:
```
(.venv) aolmedo@guybrush:~/Repos/elasticsearch-py/test_elasticsearch$ python --version
Python 2.7.15rc1
(.venv) aolmedo@guybrush:~/Repos/elasticsearch-py/test_elasticsearch$ python run_tests.py 
No elasticsearch repo found...
........................../home/aolmedo/Repos/elasticsearch-py/elasticsearch/client/utils.py:50: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  quote_plus(_escape(p), b',*') for p in parts if p not in SKIP_IN_PATH)
............................................................................................................
----------------------------------------------------------------------
Ran 134 tests in 30.944s

OK
Shutting down....
(.venv) aolmedo@guybrush:~/Repos/elasticsearch-py/test_elasticsearch$ curl http://localhost:9200
{
  "name" : "SmJ6n1V",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "S0HvL03FRW-PbKUNLAR2tw",
  "version" : {
    "number" : "6.0.1",
    "build_hash" : "601be4a",
    "build_date" : "2017-12-04T09:29:09.525Z",
    "build_snapshot" : false,
    "lucene_version" : "7.0.1",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```
Could be a partial o temporal error?

About the errors in python 3.3 all of them have the same origin: error in your deps:
```
19:53:56 PyYAML requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*' but the running Python is 3.3.7
19:53:56 You are using pip version 9.0.1, however version 19.0.3 is available.
19:53:56 You should consider upgrading via the 'pip install --upgrade pip' command.
19:53:56 Service 'client' failed to build: The command '/bin/sh -c pip install .[develop]' returned a non-zero code: 1
19:53:56 make: *** [run_tests] Error 1
```

**Comment by fxdgear** [comment]
Python3.3 is EOL and as such this entry in the matrix is going away. I'll be removing it from the test matrix in the es-7 PR.

**Comment by fxdgear** [comment]
re your python27 failure: 

```
12:56:04 
12:56:04 ======================================================================
12:56:04 FAIL: test_all_chunks_sent (test_elasticsearch.test_helpers.TestParallelBulk)
12:56:04 ----------------------------------------------------------------------
12:56:04 Traceback (most recent call last):
12:56:04   File "/usr/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
12:56:04     return func(*args, **keywargs)
12:56:04   File "/code/elasticsearch-py/test_elasticsearch/test_helpers.py", line 34, in test_all_chunks_sent
12:56:04     self.assertEquals(50, _process_bulk_chunk.call_count)
12:56:04 AssertionError: 50 != 49
```

This is a result of the fact that `mock` is not thread safe and this test runs using multi threading. It's really annoying :(

**Comment by fxdgear** [comment]
Thanks for the patch and the tests.

**Comment by alvarolmedo** [comment]
I see the error of the mock in your jenkins execution, but in my local works fine... :o

**Comment by alvarolmedo** [comment]
Thanks for accept the PR, when a new release it's scheduled?

**Pull request merged**
