### PR TITLE
Renamed the `timeout` parameter in docstring to `request_timeout` as the @query_params decorator expects `request_timeout`.

### PR DESCRIPTION
**Pull request by jubins**
The `timeout` parameter in docstring is misleading for following methods in elasticsearch.client.indices.py, renamed this param in docstring as `request_timeout`:
1. create
2. open
3. close
4. delete
5. put_mapping
6. put_alias
7. update_aliases
8. delete_alias
9. put_template
10. delete_template
11. shrink
12. rollover

### CODE REVIEW

**Comment by fxdgear** [comment]
Jenkins test this please

**Comment by fxdgear** [comment]
@jubins Thanks for the patch, but I was doing just a quick check at the decorator for the first docstring you patched and the decorator is using `timeout` and not `request_timeout`.

**Comment by jubins** [comment]
> @jubins Thanks for the patch, but I was doing just a quick check at the decorator for the first docstring you patched and the decorator is using `timeout` and not `request_timeout`.
> 
> https://github.com/elastic/elasticsearch-py/pull/891/files#diff-c0a511c3d163495efdbeb7da5404e9e7R72

@fxdgear Thanks for pointing this out, I've tested and updated query_params decorator to use `request_timeout`.

**Comment by fxdgear** [comment]
jenkins test this please

**Comment by fxdgear** [comment]
@jubins Could you please rebase this PR, I'll have jekins run the tests again afterwards. 

Thanks
n

**Comment by jubins** [comment]
> @jubins Could you please rebase this PR, I'll have jekins run the tests again afterwards.
> 
> Thanks
> n

Hi Nick,
There were some conflicts in my branch. I've retested and created another PR
https://github.com/elastic/elasticsearch-py/pull/937#issue-273968473

**Pull request closed without merging**
