### PR TITLE
Fix broken `elasticsearch-dsl` hyperlink

### PR DESCRIPTION
**Pull request by hurutoriya**
## What

~~I use `\` to escape the `-` character to fix the broken hyperlink,~~

Remove duplication of the hyperlink target `elasticsearch-dsl`.

## Why

~~Currently https://elasticsearch-py.readthedocs.io/en/v8.4.3/#id1 's `elasticsearch-dsl` hyper link is broken due to missing the escape to `-` using `\`~~

Duplication of the hyperlink target breaks elasticsearch-dsl hyper-link.

### CODE REVIEW

**Comment by miriam-eid** [comment]
Thank you for opening this PR! In this case, the problem is not missing the escape to `-`, but the duplication of the hyperlink target `elasticsearch-dsl`.
Deleting one of the links "`.. _elasticsearch-dsl: https://elasticsearch-dsl.readthedocs.io`" can solve this issue. Could you try this on your end?

**Comment by hurutoriya** [comment]
> Thank you for opening this PR! In this case, the problem is not missing the escape to `-`, but the duplication of the hyperlink target `elasticsearch-dsl`. Deleting one of the links "`.. _elasticsearch-dsl: https://elasticsearch-dsl.readthedocs.io`" can solve this issue. Could you try this on your end?

I see, Thank you for your suggestion.
I didn't know the spec of sphinx. Let me follow your suggestion.

**Comment by hurutoriya** [comment]
@miriam-eid I update baesd on your suggestion. Thank you!

https://github.com/elastic/elasticsearch-py/pull/2089/commits/b27e4b1d6c573ddf0c8a94f9ac7f2d48e69a5d95

**Comment by miriam-eid** [comment]
jenkins test this please

**Review by miriam-eid — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
