### PR TITLE
Fix docs

### PR DESCRIPTION
**Pull request by bartier**
This PR attempts to close issue #1196

As discussed in the issue, `from` is a reserved Python keyword, and parameters are passed with `from_` to avoid a syntax error. See a example below:

https://github.com/elastic/elasticsearch-py/blob/7dec9e3dbaabb2b7cc5cdb1a49370c89de72fa12/elasticsearch/client/__init__.py#L702-L704

Docs were not rendering the `_` underscore character and it would causes a syntax error if you use `from` instead of `from_`.

To correcly output underscore character it just needs a `\` before it.

Resume of changes:
- Change inside the utils/ directory as all of the code including docstrings under elasticsearch/clients/ is generated from utils/generate_api.py

Hope it helps :)

### CODE REVIEW

**Comment by bartier** [comment]
@sethmlarson Thanks for your reply. I  ran successfuly `utils/generate_api.py` after cloning elasticsearch.

In my understanding, changing only `SUBSTITUTIONS = {"type": "doc_type", "from": "from\_"}` affects places that should not be changed. (real code for example, instead of documentation, right?)

I could see some changes with my Git UI (GitKraken) after running the script (image below)

I don't understand specifically why the first diff with `included in the analysis...` appeared. Is that a change that should be there? 

The two diffs about `from` I know it is my change taking effect.
image

In essence, I need to make it work only with `:arg from_:` string to replace `from` word, right?

Thanks for your time and patience. [noob alert here haha]

**Comment by sethmlarson** [comment]
@bartier Don't worry about the "included with analysis" you shouldn't have to commit any of the changes not related to `from\_`. Your assessment of which things should change and which should not are correct, we only want docstrings to change. :)

And no worries, I'm here to help you through the process, I really appreciate you taking on this issue :D

**Comment by bartier** [comment]
@sethmlarson Hi! Is my [last commit](https://github.com/elastic/elasticsearch-py/pull/1206/commits/71a93192767329f1c5d3a1a48b415c9d37055422) a valid solution?

I've changed `utils/templates/base` like you said and committed the results of the script related to 'from'.

A lint error in CI appeared and I'm not sure how should I fix it :/ 

BTW, this PR commit history is kind of messy. Will my PR be closed automatically by GitHub if I squash all commits to generate only one (and facilitate review code process)? I ask that because my fail PR #1205 looks that this happened.

**Comment by sethmlarson** [comment]
The lint error can be seen here: https://github.com/elastic/elasticsearch-py/pull/1206/checks?check_run_id=603994279 It is caused by the `\` within the docstrings, maybe you can change it to `\\`? Either that or use `r"""` for docstring beginnings.

No worries on the commit history, I'll squash all commits to one when merging.

**Comment by bartier** [comment]
@sethmlarson I escaped `\` to fix the lint error.

Can you check it again? :)

**Comment by bartier** [comment]
@sethmlarson Now I guess everything is good. I fixed my mistakes with commit history I guess (and PR was not closed automatically haha).

**Comment by bartier** [comment]
@sethmlarson Is there anything I need to do to keep this going on or something I maybe have done wrong? :)

Thanks

**Pull request merged**
