### PR TITLE
Add search applications API to imports and generated docs

### PR DESCRIPTION
**Pull request by JoshMock**
Apparently we have to manually add new API namespaces to client.py and the sphinx API doc for them to be fully accessible to end users.

For https://github.com/elastic/elasticsearch-py/issues/2253

### CODE REVIEW

**Comment by JoshMock** [comment]
I checked the clients-ci test output and verified that none of the integration test failures were related to this change.

**Comment by szabosteve** [comment]
@pquentin @ezimuel @picandocodigo Would either of you mind taking a look at this PR and approve, please? Thank you in advance!

**Review by pquentin — APPROVED** [review]
This looks good, thanks!

image

(We can discuss the unrelated run-black.py changes after merging.)

**Comment by JoshMock** [comment]
@pquentin btw the run-black.py change was just a tweak I noticed to make it more resilient by switching to a more machine-readable format. my laptop's default `sensors` output included some false positives in the old regex.

**Pull request merged**
