### PR TITLE
Restore .ci/make.sh file

### PR DESCRIPTION
**Pull request by pquentin**
This file was removed by mistake in https://github.com/elastic/elasticsearch-py/pull/2345.

### CODE REVIEW

**Review by picandocodigo — COMMENTED** [review]
We talked about moving this file to `.github` after migrating to Buildkite, since we wouldn't need the `.ci` folder anymore. The automations already check for `make.sh` in `.github`, so it should work like before.

**Comment by pquentin** [comment]
Great point, thanks! I had forgot about this. Done, please take another look.

**Review by picandocodigo — COMMENTED** [review]
Occurrences of `.ci` need to be replaced by `.github` (or `.buildkite` in the case of Dockerfile in line 117) in the script. Other than that LGTM :+1:

**Comment by pquentin** [comment]
Another good catch! Tested with `.github/make.sh assemble 8.12.0` this time (since codegen requires a token). Please take another look.

**Review by picandocodigo — APPROVED** [review]

**Pull request merged**
