### PR TITLE
Add doc for filter_path argument in search

### PR DESCRIPTION
**Pull request by Garrett-R**
I figured out that the `search` function supported this by digging in the source.

Let me know if my way of describing it is not clear...

### CODE REVIEW

**Comment by Garrett-R** [comment]
Hmmm... I signed the CLA, but I'm still getting a fail for the CI...

**Comment by HonzaKral** [comment]
Thanks for the PR, the `filter_path` parameter actually doesn't belong to `search` but it is a global parameter accepted by all rest endpoints. It's documentation belongs to https://github.com/elastic/elasticsearch-py/blob/master/docs/api.rst#global-options instead.

**Comment by Garrett-R** [comment]
Oh yeah, good call!  Ok, how does it look now?

**Comment by HonzaKral** [comment]
Great, thank you!

**Comment by Garrett-R** [comment]
Whoa, that was fast! Thanks.

**Pull request merged**
