### PR TITLE
Fix typo in `configuration`

### PR DESCRIPTION
**Pull request by ChandanChainani**

### CODE REVIEW

**Comment by sethmlarson** [comment]
Thanks @ChandanChainani, could you [sign the CLA](https://www.elastic.co/contributor-agreement) with the same email as you've used for your commits?

**Comment by ChandanChainani** [comment]
@sethmlarson Done from my end waiting for approval
image

**Comment by ChandanChainani** [comment]
@sethmlarson Done

**Comment by sethmlarson** [comment]
@ChandanChainani I just noticed, can you rebase this PR and point it at the `main` branch? We backport all fixes from `main` into the relevant branches automatically.

**Comment by pquentin** [comment]
Sorry for missing this approved pull request! This text was removed when dropping support for Python 3.6 in https://github.com/elastic/elasticsearch-py/pull/2268/files

**Pull request closed without merging**
