### PR TITLE
Credit the authors of pyelasticsearch, from which this project draws.

### PR DESCRIPTION
**Pull request by erikrose**
Examples include the @query_params forward-compatibility decorator and the alive/dead connection pool.

Thanks; we appreciate it!

### CODE REVIEW

**Comment by tylerjharden** [comment]
Mind resolving your conflicts?

**Comment by erikrose** [comment]
@tylerjharden All set!

**Comment by duhaime** [comment]
@erikrose I think you need to sign ElasticSearch's License Agreement: https://www.elastic.co/contributor-agreement

**Comment by fxdgear** [comment]
closing. Not managing authors list manually anymore. Linking to contributors. 

https://github.com/elastic/elasticsearch-py/pull/812

**Pull request closed without merging**
