### PR TITLE
Updating Docs to reference SSL Context

### PR DESCRIPTION
**Pull request by fxdgear**

### CODE REVIEW

**Comment by fxdgear** [comment]
@HonzaKral how does this look?

**Comment by HonzaKral** [comment]
It would be nice to have the helper function exposed in `elasticsearch.connection` directly and also add some information (mainly that it is python standard and you can just pass it in) and links to ssl context docs.

Otherwise lgtm

**Comment by fxdgear** [comment]
@HonzaKral we already link to the SSL docs https://github.com/fxdgear/elasticsearch-py/blob/415b3e7dc75013ab1247e2788bf379e58190eea0/docs/connection.rst#urllib3httpconnection-default-connection_class

I'm just adding more

**Comment by fxdgear** [comment]
> It would be nice to have the helper function exposed in elasticsearch.connection directly 

so move the `create_ssl_conext` out of `http_urllib3` and into `connection`?

**Comment by HonzaKral** [comment]
I think it makes sense. We could also just import it from there, up to you...

**Comment by fxdgear** [comment]
@HonzaKral ok I updated the import. are we happy? :smile:

**Pull request merged**
