### PR TITLE
fix examples.asciidoc to match implementation

### LINKED ISSUE #2251: Inconsistent keyword argument usage in example documentation vs implementation
**Elasticsearch version**: 8.8

**`elasticsearch-py` version**: 8.8.2

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:
Documentation example vs actual implementation on the update of documents is incorrect.
The code of the [update method](https://github.com/elastic/elasticsearch-py/blob/c91b8fe17abaf5e40a2258a9cc8c473718aa7274/elasticsearch/_sync/client/__init__.py#L4448) has `doc` as keyword argument while the [official example](https://github.com/elastic/elasticsearch-py/blob/c91b8fe17abaf5e40a2258a9cc8c473718aa7274/docs/guide/examples.asciidoc?plain=1#L96) on the Elasticsearch website mentions `document`

The same documentation also still refers to `body` instead of `document` or `doc` on both the `index` and the `update` method

**Steps to reproduce**:
N/A

### PR DESCRIPTION
**Pull request by mattiassluis**
Documentation mentions wrong / outdated keyword arguments when compared to the code implementation. These fixes correct the documentation to match the implementation.

Closes #2251

### CODE REVIEW

**Comment by mattiassluis** [comment]
> ❌ Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement): [43ce85e](https://github.com/elastic/elasticsearch-py/commit/43ce85e93675ab73bbcce79a2fed9bf9574221ee)
> 
> Please, read and sign the above mentioned agreement if you want to contribute to this project

Signed

**Comment by mattiassluis** [comment]
It looks like the linter failed on unrelated code, what is the suggestion to proceed here?

**Review by pquentin — APPROVED** [review]
Thank you! This looks good to me. And sorry for the delay, we had no dedicated maintainer for some months, and this fell through the cracks.

**Comment by pquentin** [comment]
buildkite test this please

**Pull request merged**
