### PR TITLE
Custom headers in http requests with requests library 

### PR DESCRIPTION
**Pull request by haeygen**
I needed custom http headers in one of my projects. I have added a few lines of code to the requests library to support this. It is an additional parameter to init and adds these as headers.

### CODE REVIEW

**Comment by haeygen** [comment]
Ok, signed the CLA now.

**Comment by HonzaKral** [comment]
This has been already implemented in 311ac7c and will be part of next release. Thank you for the patch!

**Comment by haeygen** [comment]
HonzaKral, thanks for the info. Is it possible to see what is currently in development or planned already? I couldn't see anything about this in the milestones.

**Comment by HonzaKral** [comment]
Typically I try to put all this information into the Changelog - https://github.com/elastic/elasticsearch-py/blob/master/Changelog.rst but sometimes I fall behind. Opening a ticket is a good way to learn as well.

**Pull request closed without merging**
